/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coba;

import Koneksi.formKoneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author dina
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    Connection con = formKoneksi.getConnection();
    ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jJudul = new javax.swing.JLabel();
        fUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fPass = new javax.swing.JPasswordField();
        bSIgnUp = new javax.swing.JButton();
        bSIgnIn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jJudul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jJudul.setText("LOGIN");
        jPanel1.add(jJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));
        jPanel1.add(fUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 220, -1));

        jLabel1.setText("username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel2.setText("Belum punya akun? maka daftar dulu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel1.add(fPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 220, -1));

        bSIgnUp.setText("Sign Up");
        bSIgnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSIgnUpActionPerformed(evt);
            }
        });
        jPanel1.add(bSIgnUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 70, -1));

        bSIgnIn1.setText("Sign In");
        bSIgnIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSIgnIn1ActionPerformed(evt);
            }
        });
        jPanel1.add(bSIgnIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 70, -1));

        jLabel3.setText("password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 365, 236));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSIgnIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSIgnIn1ActionPerformed
        String User = fUser.getText();
        String Pass = fPass.getText();
        
        try {
            Statement st = con.createStatement();
            String sql = "SELECT * FROM login where username='"+User+"' and password='"+Pass+"'";
            rs = st.executeQuery(sql);
            if (rs.next()) {
                String username = rs.getString("username");
                String password = rs.getString("password");
               
                JOptionPane.showMessageDialog(null, "Selamat datang "+ username +" !");
                this.setVisible(false);//menyembunyikan layar login
                new fmenu().setVisible(true);//menampilkan layar menu
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "user dan pass salah");
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_bSIgnIn1ActionPerformed

    private void bSIgnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSIgnUpActionPerformed
                this.setVisible(false);//menyembunyikan layar login
                new fRegis().setVisible(true);//menampilkan layar menu
    }//GEN-LAST:event_bSIgnUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSIgnIn1;
    private javax.swing.JButton bSIgnUp;
    private javax.swing.JPasswordField fPass;
    private javax.swing.JTextField fUser;
    private javax.swing.JLabel jJudul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
