/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

//Library yang akan digunakan
import koneksi.formKoneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Filfimo Yulfiz Ahsanul Hulqi
 * 19102143
 * IF 07 N
 */
public class fBio extends javax.swing.JFrame {

    /**
     * Creates new form fBio
     */
    public fBio() {
        initComponents();
        tabelBio();
    }
    
    //Buat Koneksi dengan Database dbpbo
    Statement st;
    Connection con = formKoneksi.getConnection();
    ResultSet rs;
    DefaultComboBoxModel modelc;
    DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jBiodata = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jEmail = new javax.swing.JLabel();
        jJurusan = new javax.swing.JLabel();
        jNisn = new javax.swing.JLabel();
        jAlamat = new javax.swing.JLabel();
        jNmp = new javax.swing.JLabel();
        jNohp = new javax.swing.JLabel();
        tNmp = new javax.swing.JTextField();
        tEmail = new javax.swing.JTextField();
        tJurusan = new javax.swing.JTextField();
        tNisn = new javax.swing.JTextField();
        tAlamat = new javax.swing.JTextField();
        tNohp = new javax.swing.JTextField();
        jBio = new javax.swing.JLabel();
        bBatal = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        jNml = new javax.swing.JLabel();
        tNml = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbio = new javax.swing.JTable();
        bClose = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        bRefresh = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 173, 181));
        jPanel2.setPreferredSize(new java.awt.Dimension(550, 436));

        jBiodata.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jBiodata.setForeground(new java.awt.Color(238, 238, 238));
        jBiodata.setText("BIODATA MURID");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jEmail.setText("Email");

        jJurusan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jJurusan.setText("Jurusan");

        jNisn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jNisn.setText("NISN");

        jAlamat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jAlamat.setText("Alamat");

        jNmp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jNmp.setText("Nama Panggilan");

        jNohp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jNohp.setText("Nomor Hp");

        tJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJurusanActionPerformed(evt);
            }
        });

        jBio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBio.setText("Biodata Diri");

        bBatal.setText("Batal");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        jNml.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jNml.setText("Nama Lengkap");

        tNml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNmlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jNohp)
                        .addGap(58, 58, 58)
                        .addComponent(tNohp)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAlamat)
                            .addComponent(jNisn)
                            .addComponent(jJurusan)
                            .addComponent(jEmail)
                            .addComponent(jNmp)
                            .addComponent(jNml))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tNml, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(tNmp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tJurusan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNisn, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(20, 20, 20))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNml)
                    .addComponent(tNml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNmp)
                    .addComponent(tNmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmail)
                    .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jJurusan)
                    .addComponent(tJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNisn)
                    .addComponent(tNisn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAlamat)
                    .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tNohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNohp))
                .addGap(18, 18, 18)
                .addComponent(bSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBatal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbio);

        jScrollPane2.setViewportView(jScrollPane1);

        bClose.setBackground(new java.awt.Color(255, 255, 255));
        bClose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bClose.setText("X");
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRefresh)
                    .addComponent(bDelete))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBiodata)
                        .addGap(334, 334, 334)
                        .addComponent(bClose))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBiodata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Bagian tJurusan
    private void tJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJurusanActionPerformed

    //Bagian tBatal untuk membatalkan input Biodata siswa
    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        //Penanganan try-catch
        try {
            con.createStatement().executeUpdate("DELETE FROM bio where nisn ='"+tNisn.getText()+"'");
            JOptionPane.showMessageDialog(null, "Simpan dibatalkan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal membatalkan");
        }
    }//GEN-LAST:event_bBatalActionPerformed

    //Bagian bSimpan untuk menyimpan input data yang telah dimasukan kedalam
    //database
    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        String nama_leng = tNml.getText();
        String nama_pang = tNmp.getText();
        String email = tEmail.getText();
        String jurusan = tJurusan.getText();
        String nisn = tNisn.getText();
        String alamat = tAlamat.getText();
        String nohp = tNohp.getText();

        //Penanganan try-catch
        try{
            con.createStatement().executeUpdate("INSERT INTO bio value ('"+nama_leng+"','"+nama_pang+"','"+email+"','"+jurusan+"','"+nisn+"','"+alamat+"','"+nohp+"')");
            JOptionPane.showMessageDialog(null, "Berhasil menyimpan");
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan!");
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    //Bagian tNml
    private void tNmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNmlActionPerformed

    //Bagian tbio untuk tabel bio event
    private void tbioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbioMouseClicked
        int i = this.tbio.getSelectedRow();// i adalah baris yang di klik

        String nama_leng = (String) model.getValueAt(i, 0);
        this.tNml.setText(nama_leng);
        String nama_pang = (String) model.getValueAt(i, 1);
        this.tNmp.setText(nama_pang);
        String email = (String) model.getValueAt(i, 2);
        this.tEmail.setText(email);
        String jurusan = (String) model.getValueAt(i, 3);
        this.tJurusan.setText(jurusan);
        String nisn = (String) model.getValueAt(i, 4);
        this.tNisn.setText(nisn);
        String alamat = (String) model.getValueAt(i, 5);
        this.tAlamat.setText(alamat);
        String noHP = (String) model.getValueAt(i, 6);
        this.tNohp.setText(noHP);

        //Mematikan form item agar tidak bisa dirubah
        tNisn.setEnabled(false);
    }//GEN-LAST:event_tbioMouseClicked

    //Bagian bClose untuk menutup halaman
    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        // TODO add your handling code here:
        new fmenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bCloseActionPerformed

    //Bagian bRefresh untuk merefresh halaman agar update
    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        // TODO add your handling code here:
        resetForm();
        bSimpan.setEnabled(true);
    }//GEN-LAST:event_bRefreshActionPerformed

    //Bagian bDelete untuk menghapus data yang dipilih
    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
        try {
            con.createStatement().executeUpdate("DELETE FROM bio where nisn ='"+tNisn.getText()+"'");
            JOptionPane.showMessageDialog(null, "berhasil");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "gagal");
        }
        resetForm();
    }//GEN-LAST:event_bDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fBio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fBio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fBio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fBio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fBio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JButton bClose;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bSimpan;
    private javax.swing.JLabel jAlamat;
    private javax.swing.JLabel jBio;
    private javax.swing.JLabel jBiodata;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jJurusan;
    private javax.swing.JLabel jNisn;
    private javax.swing.JLabel jNml;
    private javax.swing.JLabel jNmp;
    private javax.swing.JLabel jNohp;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tJurusan;
    private javax.swing.JTextField tNisn;
    private javax.swing.JTextField tNml;
    private javax.swing.JTextField tNmp;
    private javax.swing.JTextField tNohp;
    private javax.swing.JTable tbio;
    // End of variables declaration//GEN-END:variables

    //Pembuatan method baru untuk tabelBio
    private void tabelBio() {
        String[] judul = {"Nama Lengkap","Nama Panggilan","Email","Jurusan","NISN","Alamat", "Nomor Hp"};
        model = new DefaultTableModel(judul,0);
        tbio.setModel(model);
        //Memilih data dari SQL
        String sql = "SELECT * FROM bio";
        
        //Penanganan try-catch
        try {
            rs = con.createStatement().executeQuery(sql);
            
            while(rs.next()) {
               String nama_leng = rs.getString("namaL");
               String nama_pang = rs.getString("namaP");
               String email = rs.getString("email");
               String jurusan = rs.getString("jurusan");
               String nisn = rs.getString("nisn");
               String alamat = rs.getString("alamat");
               String nohp = rs.getString("noHP");

               String[] data = {nama_leng, nama_pang, email, jurusan, nisn, alamat, nohp};
               model.addRow(data);
           }
        }catch(SQLException e) {
           System.out.println(e);
        }
    }
    
    //Pembuatan method baru untuk resetForm
    public void resetForm(){
        tNml.setText("");
        tNmp.setText(""); 
        tEmail.setText("");
        tJurusan.setText(""); 
        tNisn.setText(""); 
        tAlamat.setText("");
        tNohp.setText("");
        
        tabelBio();
        bSimpan.setEnabled(true);
        tNml.setEnabled(true);
    }
}
